/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package dke.tradesim.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PortfolioValueHistory implements org.apache.thrift.TBase<PortfolioValueHistory, PortfolioValueHistory._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PortfolioValueHistory");

  private static final org.apache.thrift.protocol.TField PORTFOLIO_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("portfolioValues", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PortfolioValueHistoryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PortfolioValueHistoryTupleSchemeFactory());
  }

  public List<PortfolioValue> portfolioValues; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PORTFOLIO_VALUES((short)1, "portfolioValues");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PORTFOLIO_VALUES
          return PORTFOLIO_VALUES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PORTFOLIO_VALUES, new org.apache.thrift.meta_data.FieldMetaData("portfolioValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PortfolioValue.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PortfolioValueHistory.class, metaDataMap);
  }

  public PortfolioValueHistory() {
  }

  public PortfolioValueHistory(
    List<PortfolioValue> portfolioValues)
  {
    this();
    this.portfolioValues = portfolioValues;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PortfolioValueHistory(PortfolioValueHistory other) {
    if (other.isSetPortfolioValues()) {
      List<PortfolioValue> __this__portfolioValues = new ArrayList<PortfolioValue>();
      for (PortfolioValue other_element : other.portfolioValues) {
        __this__portfolioValues.add(new PortfolioValue(other_element));
      }
      this.portfolioValues = __this__portfolioValues;
    }
  }

  public PortfolioValueHistory deepCopy() {
    return new PortfolioValueHistory(this);
  }

  @Override
  public void clear() {
    this.portfolioValues = null;
  }

  public int getPortfolioValuesSize() {
    return (this.portfolioValues == null) ? 0 : this.portfolioValues.size();
  }

  public java.util.Iterator<PortfolioValue> getPortfolioValuesIterator() {
    return (this.portfolioValues == null) ? null : this.portfolioValues.iterator();
  }

  public void addToPortfolioValues(PortfolioValue elem) {
    if (this.portfolioValues == null) {
      this.portfolioValues = new ArrayList<PortfolioValue>();
    }
    this.portfolioValues.add(elem);
  }

  public List<PortfolioValue> getPortfolioValues() {
    return this.portfolioValues;
  }

  public PortfolioValueHistory setPortfolioValues(List<PortfolioValue> portfolioValues) {
    this.portfolioValues = portfolioValues;
    return this;
  }

  public void unsetPortfolioValues() {
    this.portfolioValues = null;
  }

  /** Returns true if field portfolioValues is set (has been assigned a value) and false otherwise */
  public boolean isSetPortfolioValues() {
    return this.portfolioValues != null;
  }

  public void setPortfolioValuesIsSet(boolean value) {
    if (!value) {
      this.portfolioValues = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PORTFOLIO_VALUES:
      if (value == null) {
        unsetPortfolioValues();
      } else {
        setPortfolioValues((List<PortfolioValue>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PORTFOLIO_VALUES:
      return getPortfolioValues();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PORTFOLIO_VALUES:
      return isSetPortfolioValues();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PortfolioValueHistory)
      return this.equals((PortfolioValueHistory)that);
    return false;
  }

  public boolean equals(PortfolioValueHistory that) {
    if (that == null)
      return false;

    boolean this_present_portfolioValues = true && this.isSetPortfolioValues();
    boolean that_present_portfolioValues = true && that.isSetPortfolioValues();
    if (this_present_portfolioValues || that_present_portfolioValues) {
      if (!(this_present_portfolioValues && that_present_portfolioValues))
        return false;
      if (!this.portfolioValues.equals(that.portfolioValues))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PortfolioValueHistory other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PortfolioValueHistory typedOther = (PortfolioValueHistory)other;

    lastComparison = Boolean.valueOf(isSetPortfolioValues()).compareTo(typedOther.isSetPortfolioValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPortfolioValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.portfolioValues, typedOther.portfolioValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PortfolioValueHistory(");
    boolean first = true;

    sb.append("portfolioValues:");
    if (this.portfolioValues == null) {
      sb.append("null");
    } else {
      sb.append(this.portfolioValues);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PortfolioValueHistoryStandardSchemeFactory implements SchemeFactory {
    public PortfolioValueHistoryStandardScheme getScheme() {
      return new PortfolioValueHistoryStandardScheme();
    }
  }

  private static class PortfolioValueHistoryStandardScheme extends StandardScheme<PortfolioValueHistory> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PortfolioValueHistory struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PORTFOLIO_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.portfolioValues = new ArrayList<PortfolioValue>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  PortfolioValue _elem10; // optional
                  _elem10 = new PortfolioValue();
                  _elem10.read(iprot);
                  struct.portfolioValues.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setPortfolioValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PortfolioValueHistory struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.portfolioValues != null) {
        oprot.writeFieldBegin(PORTFOLIO_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.portfolioValues.size()));
          for (PortfolioValue _iter11 : struct.portfolioValues)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PortfolioValueHistoryTupleSchemeFactory implements SchemeFactory {
    public PortfolioValueHistoryTupleScheme getScheme() {
      return new PortfolioValueHistoryTupleScheme();
    }
  }

  private static class PortfolioValueHistoryTupleScheme extends TupleScheme<PortfolioValueHistory> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PortfolioValueHistory struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPortfolioValues()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPortfolioValues()) {
        {
          oprot.writeI32(struct.portfolioValues.size());
          for (PortfolioValue _iter12 : struct.portfolioValues)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PortfolioValueHistory struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.portfolioValues = new ArrayList<PortfolioValue>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            PortfolioValue _elem15; // optional
            _elem15 = new PortfolioValue();
            _elem15.read(iprot);
            struct.portfolioValues.add(_elem15);
          }
        }
        struct.setPortfolioValuesIsSet(true);
      }
    }
  }

}

