/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package dke.tradesim.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SecurityIds implements org.apache.thrift.TBase<SecurityIds, SecurityIds._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SecurityIds");

  private static final org.apache.thrift.protocol.TField SECURITY_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("securityIds", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SecurityIdsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SecurityIdsTupleSchemeFactory());
  }

  public List<Integer> securityIds; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SECURITY_IDS((short)1, "securityIds");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SECURITY_IDS
          return SECURITY_IDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SECURITY_IDS, new org.apache.thrift.meta_data.FieldMetaData("securityIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SecurityIds.class, metaDataMap);
  }

  public SecurityIds() {
  }

  public SecurityIds(
    List<Integer> securityIds)
  {
    this();
    this.securityIds = securityIds;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SecurityIds(SecurityIds other) {
    if (other.isSetSecurityIds()) {
      List<Integer> __this__securityIds = new ArrayList<Integer>();
      for (Integer other_element : other.securityIds) {
        __this__securityIds.add(other_element);
      }
      this.securityIds = __this__securityIds;
    }
  }

  public SecurityIds deepCopy() {
    return new SecurityIds(this);
  }

  @Override
  public void clear() {
    this.securityIds = null;
  }

  public int getSecurityIdsSize() {
    return (this.securityIds == null) ? 0 : this.securityIds.size();
  }

  public java.util.Iterator<Integer> getSecurityIdsIterator() {
    return (this.securityIds == null) ? null : this.securityIds.iterator();
  }

  public void addToSecurityIds(int elem) {
    if (this.securityIds == null) {
      this.securityIds = new ArrayList<Integer>();
    }
    this.securityIds.add(elem);
  }

  public List<Integer> getSecurityIds() {
    return this.securityIds;
  }

  public SecurityIds setSecurityIds(List<Integer> securityIds) {
    this.securityIds = securityIds;
    return this;
  }

  public void unsetSecurityIds() {
    this.securityIds = null;
  }

  /** Returns true if field securityIds is set (has been assigned a value) and false otherwise */
  public boolean isSetSecurityIds() {
    return this.securityIds != null;
  }

  public void setSecurityIdsIsSet(boolean value) {
    if (!value) {
      this.securityIds = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SECURITY_IDS:
      if (value == null) {
        unsetSecurityIds();
      } else {
        setSecurityIds((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SECURITY_IDS:
      return getSecurityIds();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SECURITY_IDS:
      return isSetSecurityIds();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SecurityIds)
      return this.equals((SecurityIds)that);
    return false;
  }

  public boolean equals(SecurityIds that) {
    if (that == null)
      return false;

    boolean this_present_securityIds = true && this.isSetSecurityIds();
    boolean that_present_securityIds = true && that.isSetSecurityIds();
    if (this_present_securityIds || that_present_securityIds) {
      if (!(this_present_securityIds && that_present_securityIds))
        return false;
      if (!this.securityIds.equals(that.securityIds))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(SecurityIds other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    SecurityIds typedOther = (SecurityIds)other;

    lastComparison = Boolean.valueOf(isSetSecurityIds()).compareTo(typedOther.isSetSecurityIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSecurityIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.securityIds, typedOther.securityIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SecurityIds(");
    boolean first = true;

    sb.append("securityIds:");
    if (this.securityIds == null) {
      sb.append("null");
    } else {
      sb.append(this.securityIds);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SecurityIdsStandardSchemeFactory implements SchemeFactory {
    public SecurityIdsStandardScheme getScheme() {
      return new SecurityIdsStandardScheme();
    }
  }

  private static class SecurityIdsStandardScheme extends StandardScheme<SecurityIds> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SecurityIds struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SECURITY_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.securityIds = new ArrayList<Integer>(_list16.size);
                for (int _i17 = 0; _i17 < _list16.size; ++_i17)
                {
                  int _elem18; // optional
                  _elem18 = iprot.readI32();
                  struct.securityIds.add(_elem18);
                }
                iprot.readListEnd();
              }
              struct.setSecurityIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SecurityIds struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.securityIds != null) {
        oprot.writeFieldBegin(SECURITY_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.securityIds.size()));
          for (int _iter19 : struct.securityIds)
          {
            oprot.writeI32(_iter19);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SecurityIdsTupleSchemeFactory implements SchemeFactory {
    public SecurityIdsTupleScheme getScheme() {
      return new SecurityIdsTupleScheme();
    }
  }

  private static class SecurityIdsTupleScheme extends TupleScheme<SecurityIds> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SecurityIds struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSecurityIds()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetSecurityIds()) {
        {
          oprot.writeI32(struct.securityIds.size());
          for (int _iter20 : struct.securityIds)
          {
            oprot.writeI32(_iter20);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SecurityIds struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.securityIds = new ArrayList<Integer>(_list21.size);
          for (int _i22 = 0; _i22 < _list21.size; ++_i22)
          {
            int _elem23; // optional
            _elem23 = iprot.readI32();
            struct.securityIds.add(_elem23);
          }
        }
        struct.setSecurityIdsIsSet(true);
      }
    }
  }

}

