/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package dke.tradesim.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TransactionType implements org.apache.thrift.TEnum {
  ORDER(1),
  SPLIT_ADJUSTMENT(2),
  CASH_DIVIDEND_PAYMENT(3);

  private final int value;

  private TransactionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TransactionType findByValue(int value) { 
    switch (value) {
      case 1:
        return ORDER;
      case 2:
        return SPLIT_ADJUSTMENT;
      case 3:
        return CASH_DIVIDEND_PAYMENT;
      default:
        return null;
    }
  }
}
